use CICD;
use schema DRAI_CICD;

CREATE OR REPLACE TABLE SP_SALES_PREMIUM (
    sale_id        NUMBER,
    product_id     NUMBER,
    quantity       NUMBER,
    sale_amount    NUMBER(10,2)
);

CREATE OR REPLACE FILE FORMAT DRAI_CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"';


CREATE OR REPLACE STORAGE INTEGRATION DRAI_SP_S3_INBOUND
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = S3
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::938674806641:role/drai_snf_snowpipe_role1'
    STORAGE_ALLOWED_LOCATIONS = ('s3://datalake-dev-dtrai-snowpipe-in-com/drai/sp_inbound/');

DESC INTEGRATION DRAI_SP_S3_INBOUND;


CREATE OR REPLACE STAGE DRAI_SP_S3_STG_INBOUND
    URL = 's3://datalake-dev-dtrai-snowpipe-in-com/drai/sp_inbound/'
    STORAGE_INTEGRATION = DRAI_SP_S3_INBOUND
    FILE_FORMAT = DRAI_CSV_FORMAT;

CREATE OR REPLACE PIPE DRAI_SNOWPIPE_SALES
    AUTO_INGEST = TRUE
    AS
    COPY INTO SP_SALES_PREMIUM
    FROM @DRAI_SP_S3_STG_INBOUND/sales_premium
    FILE_FORMAT = (FORMAT_NAME = DRAI_CSV_FORMAT)
    ON_ERROR = 'CONTINUE';


-- DROP PIPE IF EXISTS DRAI_SNOWPIPE_SALES;
    
-- TRUNCATE TABLE SP_SALES_PREMIUM;
-- DESC PIPE DRAI_SNOWPIPE_SALES;

SELECT * FROM SP_SALES_PREMIUM;

-- SELECT SYSTEM$PIPE_STATUS('DRAI_SNOWPIPE_SALES');



